-- MySQL Script generated by MySQL Workbench
-- Fri Jun 25 21:50:22 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema objcloud
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema objcloud
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `objcloud` DEFAULT CHARACTER SET utf8 ;
USE `objcloud` ;

-- -----------------------------------------------------
-- Table `objcloud`.`t_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `objcloud`.`t_user` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '用户id',
  `nickname` VARCHAR(32) NOT NULL COMMENT '昵称',
  `photo` VARCHAR(255) NOT NULL COMMENT '头像',
  `password` VARCHAR(256) NOT NULL COMMENT '密码',
  `account` VARCHAR(20) NOT NULL COMMENT '账号',
  `isDisable` BIT NOT NULL DEFAULT 0 COMMENT '是否停用',
  `createtime` CHAR(19) NOT NULL,
  `del` BIT NOT NULL DEFAULT 0 COMMENT '是否删除 0 — 未删除 1— 删除',
  `deltime` CHAR(19) NULL COMMENT '数据删除时间\n',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `objcloud`.`t_file_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `objcloud`.`t_file_type` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '类型id',
  `type` VARCHAR(32) NULL COMMENT '类型名称',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `objcloud`.`t_files_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `objcloud`.`t_files_status` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '文件状态id',
  `status` CHAR(1) NOT NULL COMMENT '文件状态',
  `del` BIT NOT NULL DEFAULT 1 COMMENT '状态是否删除',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `objcloud`.`t_files`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `objcloud`.`t_files` (
  `sha256` VARCHAR(512) NOT NULL COMMENT '文件Sha256Id',
  `url` VARCHAR(255) NOT NULL COMMENT '文件路径',
  `status_id` INT NOT NULL COMMENT '状态Id',
  `file_type_id` INT NOT NULL COMMENT '文件类型id',
  PRIMARY KEY (`sha256`),
  INDEX `fk_t_files_t_filetype_idx` (`status_id` ASC) VISIBLE,
  INDEX `fk_t_files_t_filestatus1_idx` (`file_type_id` ASC) VISIBLE,
  CONSTRAINT `fk_t_files_t_filetype`
    FOREIGN KEY (`status_id`)
    REFERENCES `objcloud`.`t_file_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_files_t_filestatus1`
    FOREIGN KEY (`file_type_id`)
    REFERENCES `objcloud`.`t_files_status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `objcloud`.`t_user_files`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `objcloud`.`t_user_files` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '用户文件id',
  `file_id` VARCHAR(512) NOT NULL COMMENT '文件Sha256Id',
  `file_name` VARCHAR(255) NOT NULL COMMENT '文件名',
  `folder_id` INT NULL COMMENT '文件夹id',
  `user_id` INT NOT NULL COMMENT '用户id',
  `open` BIT NOT NULL DEFAULT 0 COMMENT '是否公开',
  `suffix` VARCHAR(45) NOT NULL COMMENT '文件后缀名',
  `create_time` CHAR(19) NOT NULL COMMENT '添加时间',
  `del` BIT NOT NULL DEFAULT 0 COMMENT '是否删除 0 — 未删除 1 — 已删除',
  `del_time` CHAR(19) NULL COMMENT '删除时间',
  PRIMARY KEY (`id`),
  INDEX `fk_t_user_files_t_files1_idx` (`file_id` ASC) VISIBLE,
  INDEX `fk_t_user_files_t_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_t_user_files_t_files1`
    FOREIGN KEY (`file_id`)
    REFERENCES `objcloud`.`t_files` (`sha256`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_user_files_t_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `objcloud`.`t_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `objcloud`.`t_folder`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `objcloud`.`t_folder` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '文件夹id',
  `name` VARCHAR(64) NOT NULL COMMENT '文件夹名称',
  `user_id` INT NOT NULL COMMENT '用户id',
  `folder_id` INT NULL COMMENT '文件夹id',
  `size` DOUBLE NOT NULL COMMENT '文件夹大小',
  `create_time` CHAR(19) NOT NULL COMMENT '创建时间\n',
  `del` BIT NOT NULL DEFAULT 0 COMMENT '是否删除 0 — 未删除 1 — 已删除',
  `del_time` CHAR(19) NULL COMMENT '删除时间',
  INDEX `fk_t_favlist_t_user1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_t_favlist_t_favlist1_idx` (`folder_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_t_favlist_t_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `objcloud`.`t_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_favlist_t_favlist1`
    FOREIGN KEY (`folder_id`)
    REFERENCES `objcloud`.`t_folder` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
